spring.application.name=notification-service
server.port=8084
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
fluxnova.bpm.job-execution.deployment-aware=true
fluxnova.bpm.job-execution.enabled=true
