services:
  db:
    image: postgres:16-alpine
    container_name: postgres_db
    restart: always
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  oracle-db:
    image: gvenzl/oracle-free:latest
    container_name: oracle_db
    restart: always
    environment:
      - ORACLE_PASSWORD=${ORACLE_PASSWORD}
      - APP_USER=${ORACLE_APP_USER}
      - APP_USER_PASSWORD=${ORACLE_APP_PASSWORD}
    ports:
      - "1521:1521"
    volumes:
      - oracle_data:/opt/oracle/oradata

volumes:
  postgres_data:
  oracle_data: