server.port=8090
spring.application.name=api-gateway

# Gateway Routes Setup
spring.cloud.gateway.routes[0].id=user-service
spring.cloud.gateway.routes[0].uri=http://localhost:8086
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/users/**

spring.cloud.gateway.routes[1].id=group-service
spring.cloud.gateway.routes[1].uri=http://localhost:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/groups/**

spring.cloud.gateway.routes[2].id=event-service
spring.cloud.gateway.routes[2].uri=http://localhost:8083
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/events/**

spring.cloud.gateway.routes[3].id=rsvp-service
spring.cloud.gateway.routes[3].uri=http://localhost:8085
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/rsvps/**

spring.cloud.gateway.routes[4].id=auth-service
spring.cloud.gateway.routes[4].uri=http://localhost:8091
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/auth/**

# Enable Gateway endpoints for Actuator
management.endpoints.web.exposure.include=gateway,health
