spring.application.name=fluxnova-webapp-component
server.port=8080
spring.config.import=optional:file:.env[.properties],optional:file:../.env[.properties]

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Disable job execution on this node since it only serves REST/Web UI
fluxnova.bpm.job-execution.enabled=false
fluxnova.bpm.job-execution.deployment-aware=true
