spring.application.name=user-service
server.port=8086
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/myappdb}
spring.datasource.username=${DB_USERNAME:composeuser}
spring.datasource.password=${DB_PASSWORD:composepass}
fluxnova.bpm.job-execution.deployment-aware=true
fluxnova.bpm.job-execution.enabled=true

# JPA/Hibernate Configs
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# JWT Security Configs
jwt.secret=showupjwtsecretkeythatmustbeatleast256bitslongforsecurityreasons!
jwt.expiration-ms=86400000
