spring.application.name=fluxnova-cleanup-component
spring.main.web-application-type=none
spring.config.import=optional:file:.env[.properties],optional:file:../.env[.properties]

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Disable job execution on this node (since it only runs scheduled cleanup tasks via Spring, not Fluxnova engine tasks)
fluxnova.bpm.job-execution.enabled=false
fluxnova.bpm.job-execution.deployment-aware=true

# Cleanup configurations
cleanup.hanging-instances.threshold-days=30
cleanup.old-deployments.keep-versions=3

# History Cleanup Configuration (Finos Fluxnova / Camunda 7 Engine properties)
fluxnova.bpm.generic-properties.properties.historyCleanupEnabled=true
fluxnova.bpm.generic-properties.properties.historyCleanupStrategy=removalTimeBased
fluxnova.bpm.generic-properties.properties.historyCleanupBatchWindowStartTime=00:00
fluxnova.bpm.generic-properties.properties.historyCleanupBatchWindowEndTime=23:59

